### ISSUE TITLE
Doesn't work with redmine 4.0.4

### ISSUE THREAD

**Issue by yennor** [jgraichen/redmine_dashboard#141]
I've got redmine running on Debian buster, with the current backport package.
I've tried to install the last released 2.8.0.zip, and also to directly clone the current 2-branch. But in either cases I get following message:

```
[ 2020-02-19 14:59:40.7625 32763/7f0d6d6b4700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /usr/share/redmine: An error occurred while starting up the preloader.
  Error ID: 1fa54228
  Error details saved to: /tmp/passenger-error-sKKmsr.html
  Message from application: undefined method `before_filter' for RdbDashboardController:Class
Did you mean?  before_action (NoMethodError)
  /usr/share/redmine/plugins/redmine_checklists/lib/redmine_checklists/patches/compatibility/application_controller_patch.rb:32:in `before_action'
  /usr/share/redmine/plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb:4:in `<class:RdbDashboardController>'
  /usr/share/redmine/plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb:1:in `<top (required)>'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:37:in `load_interlock'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:356:in `require_or_load'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:334:in `depend_on'
  /usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:246:in `require_dependency'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `each'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `each'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `eager_load!'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:356:in `eager_load!'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `each'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
  /usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
  /usr/share/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
  /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/pass

enger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by jgraichen** [comment]
This appears to be an issue with Redmine Checklists as indicated by the top line:

```
/usr/share/redmine/plugins/redmine_checklists/lib/redmine_checklists/patches/compatibility/application_controller_patch.rb:32:in `before_action'
```

From the error message I'd they that the installed Redmine Checklist version is not compatible with the running Redmine version. Redmine Dashboard itself is continuously and automatically tested with all recent Redmine versions ([see here](https://github.com/jgraichen/redmine_dashboard/actions/runs/34994683))

**Comment by yennor** [comment]
ok. sorry, my fault, seems like I've only noticed the 2nd and 3th line...

It seems like redmine checklist and redmin dashboard are incompatible to each other. When I remove either of the plugin, the other one works...

**Comment by jgraichen** [comment]
Redmine Checklists seems to include some patches effecting a lot of other plugins: https://github.com/danmunn/redmine_dmsf/issues/1061.

Please report this issue at https://www.redmineup.com/.

Unfortunately I cannot find the source code of redmine_checklists matching the above lines and therefore cannot help you any more.
