### ISSUE TITLE
rdbDADShowIssue is not a function

### ISSUE THREAD

**Issue by qawsed55** [jgraichen/redmine_dashboard#364]
When drug issue I see LOADING popup (java as I think) and nothing happens. Issue, that I drug - dissapiering.
In console - I see this error:

```
XHRGEThttp://192.168.0.250/projects/sbytsnab/rdb/taskboard/move?issue=724&lock_version=21&column=s50&group=all&_=1678380386554
[HTTP/1.1 500 Internal Server Error 141ms]

Uncaught TypeError: $().rdbDADShowIssue is not a function
    drop http://192.168.0.250/plugin_assets/redmine_dashboard/javascripts/dashboard.taskboard.js?1678380353:78
    jQuery 8
        c
        fireWith
        l
        o
        send
        ajax
        i
        getScript
    drop http://192.168.0.250/plugin_assets/redmine_dashboard/javascripts/dashboard.taskboard.js?1678380353:75
    jQuery 24
        _trigger
        _drop
        i
        drop
        each
        drop
        _mouseStop
        i
        _mouseUp
        i
        _mouseUp
        i
        _mouseUpDelegate
        dispatch
        handle
        add
        Ee
        each
        each
        Ee
        on
        <anonymous>
        <anonymous>
        <anonymous>

```
After page refreshing I see, that issue status changed well.
In other words I need to refresh page to see result after issue drugging on dashboard.

**Comment by jgraichen** [comment]
There also is a server error (`[HTTP/1.1 500 Internal Server Error 141ms]`). Please provide the following information or [*use the bug report template and answer the questions*](https://github.com/jgraichen/redmine_dashboard/issues/new?assignees=&labels=bug&template=bug_report.md&title=rdbDADShowIssue+is+not+a+function):

**Redmine**

```
<Redmine details (or screenshot) from Redmine > Administration > Information (/admin/info)>
```

```
<Redmine server log>
```

**Details about your server**

- OS: [e.g. Ubuntu 20.04]
- Appliance: [e.g. Bitnami, docker, ... for example with link to source]

**Client information**

- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]

**Comment by qawsed55** [comment]
https://youtu.be/KWGJlpW_OEc

here I'm record what happening.
Every page reload - there are error after changing status.

This is all log from  `/opt/redmine/log/production.log`

```
I, [2023-03-10T07:51:02.854888 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f] Started GET "/projects/sbytsnab/rdb/taskboard/move?issue=724&lock_version=24&column=s50&group=all&_=1678423794840" for 192.168.3.222 at 2023-03-10>
I, [2023-03-10T07:51:02.855489 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f] Processing by RdbTaskboardController#move as JS
I, [2023-03-10T07:51:02.855518 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f]   Parameters: {"issue"=>"724", "lock_version"=>"24", "column"=>"s50", "group"=>"all", "_"=>"1678423794840", "id"=>"sbytsnab"}
I, [2023-03-10T07:51:02.876896 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f]   Current user: drobyshev (id=43)
I, [2023-03-10T07:51:02.971002 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f] [ActiveJob] Enqueued MessengerDeliverJob (Job ID: e7e2ebf0-32b8-4b70-8123-afc9f07f7669) to Async(default) with arguments: "https://geo.rocket.chat>
I, [2023-03-10T07:51:02.971546 #150502]  INFO -- : [ActiveJob] [MessengerDeliverJob] [e7e2ebf0-32b8-4b70-8123-afc9f07f7669] Performing MessengerDeliverJob (Job ID: e7e2ebf0-32b8-4b70-8123-afc9f07f7669) from Async(default) enqueued at 20>
I, [2023-03-10T07:51:02.992123 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 689e175b-39ad-4b03-bf22-4458f1471d80) to Async(mailers) with arguments: "Mailer", "iss>
I, [2023-03-10T07:51:02.993116 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c) to Async(mailers) with arguments: "Mailer", "iss>
I, [2023-03-10T07:51:02.996251 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [689e175b-39ad-4b03-bf22-4458f1471d80] Performing ActionMailer::MailDeliveryJob (Job ID: 689e175b-39ad-4b03-bf22-4458f1471d80) from Async(mai>
I, [2023-03-10T07:51:02.998960 #150502]  INFO -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f] Completed 500 Internal Server Error in 143ms (ActiveRecord: 49.7ms | Allocations: 74800)
F, [2023-03-10T07:51:03.000484 #150502] FATAL -- : [eb73df07-5210-4526-9cb1-0f334c12cf4f]
[eb73df07-5210-4526-9cb1-0f334c12cf4f] NoMethodError (undefined method `map' for nil:NilClass):
[eb73df07-5210-4526-9cb1-0f334c12cf4f]
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/app/models/journal_checklist_history.rb:139:in `force_object'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/app/models/journal_checklist_history.rb:60:in `initialize'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/lib/redmine_checklists/hooks/controller_issues_hook.rb:27:in `new'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/lib/redmine_checklists/hooks/controller_issues_hook.rb:27:in `controller_issues_edit_after_save'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/hook.rb:66:in `each'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/hook.rb:66:in `block in call_hook'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/hook.rb:63:in `tap'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/hook.rb:63:in `call_hook'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/hook.rb:96:in `call_hook'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_dashboard/app/controllers/rdb_taskboard_controller.rb:57:in `update'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_dashboard/app/controllers/rdb_taskboard_controller.rb:25:in `move'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
I, [2023-03-10T07:51:03.028582 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [689e175b-39ad-4b03-bf22-4458f1471d80]   Rendered mailer/issue_edit.text.erb within layouts/mailer (Duration: 15.9ms | Allocations: 10150)
I, [2023-03-10T07:51:03.029986 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [689e175b-39ad-4b03-bf22-4458f1471d80]   Rendered layout layouts/mailer.text.erb (Duration: 17.4ms | Allocations: 10774)
I, [2023-03-10T07:51:03.036341 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [689e175b-39ad-4b03-bf22-4458f1471d80]   Rendered mailer/issue_edit.html.erb within layouts/mailer (Duration: 3.4ms | Allocations: 3223)
I, [2023-03-10T07:51:03.038429 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [689e175b-39ad-4b03-bf22-4458f1471d80]   Rendered layout layouts/mailer.html.erb (Duration: 5.5ms | Allocations: 4227)
I, [2023-03-10T07:51:03.045016 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [689e175b-39ad-4b03-bf22-4458f1471d80] Performed ActionMailer::MailDeliveryJob (Job ID: 689e175b-39ad-4b03-bf22-4458f1471d80) from Async(mail>
I, [2023-03-10T07:51:03.046946 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c] Performing ActionMailer::MailDeliveryJob (Job ID: c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c) from Async(mai>
I, [2023-03-10T07:51:03.062807 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c]   Rendered mailer/issue_edit.text.erb within layouts/mailer (Duration: 7.7ms | Allocations: 3612)
I, [2023-03-10T07:51:03.063017 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c]   Rendered layout layouts/mailer.text.erb (Duration: 7.9ms | Allocations: 3678)
I, [2023-03-10T07:51:03.064825 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c]   Rendered mailer/issue_edit.html.erb within layouts/mailer (Duration: 1.6ms | Allocations: 1154)
I, [2023-03-10T07:51:03.065200 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c]   Rendered layout layouts/mailer.html.erb (Duration: 1.9ms | Allocations: 1417)
I, [2023-03-10T07:51:03.071626 #150502]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c] Performed ActionMailer::MailDeliveryJob (Job ID: c5d7cc1a-8847-4a8c-a0ed-e3b4cb68e18c) from Async(mail>
I, [2023-03-10T07:51:05.327595 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c] Started GET "/projects/sbytsnab/rdb/taskboard" for 192.168.3.222 at 2023-03-10 07:51:05 +0300
I, [2023-03-10T07:51:05.328146 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c] Processing by RdbTaskboardController#index as HTML
I, [2023-03-10T07:51:05.328172 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c]   Parameters: {"id"=>"sbytsnab"}
I, [2023-03-10T07:51:05.330694 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c]   Current user: drobyshev (id=43)
I, [2023-03-10T07:51:05.343288 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c]   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.html.slim within layouts/base (Duration: 1.5ms | Allocations: 1149)
I, [2023-03-10T07:51:05.358974 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c]   Rendered layout layouts/base.html.erb (Duration: 17.2ms | Allocations: 13180)
I, [2023-03-10T07:51:05.363537 #150502]  INFO -- : [7a78c391-0174-4e76-9f9d-98616b86259c] Completed 200 OK in 35ms (Views: 14.0ms | ActiveRecord: 7.9ms | Allocations: 23747)
I, [2023-03-10T07:51:05.473546 #150502]  INFO -- : [2ee81447-224e-4402-9b34-e1d2d5117a26] Started GET "/projects/sbytsnab/rdb/taskboard?&_=1678423866299" for 192.168.3.222 at 2023-03-10 07:51:05 +0300
I, [2023-03-10T07:51:05.474087 #150502]  INFO -- : [2ee81447-224e-4402-9b34-e1d2d5117a26] Processing by RdbTaskboardController#index as JS
I, [2023-03-10T07:51:05.474115 #150502]  INFO -- : [2ee81447-224e-4402-9b34-e1d2d5117a26]   Parameters: {"_"=>"1678423866299", "id"=>"sbytsnab"}
I, [2023-03-10T07:51:05.476627 #150502]  INFO -- : [2ee81447-224e-4402-9b34-e1d2d5117a26]   Current user: drobyshev (id=43)
I, [2023-03-10T07:51:05.569497 #150502]  INFO -- : [2ee81447-224e-4402-9b34-e1d2d5117a26]   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb (Duration: 80.8ms | Allocations: 53955)
I, [2023-03-10T07:51:05.573930 #150502]  INFO -- : [2ee81447-224e-4402-9b34-e1d2d5117a26] Completed 200 OK in 100ms (Views: 65.4ms | ActiveRecord: 20.7ms | Allocations: 64691)
W, [2023-03-10T07:51:06.537021 #150502]  WARN -- : [ActiveJob] [MessengerDeliverJob] [e7e2ebf0-32b8-4b70-8123-afc9f07f7669] #<Net::HTTPOK 200 OK readbody=true>
I, [2023-03-10T07:51:06.537189 #150502]  INFO -- : [ActiveJob] [MessengerDeliverJob] [e7e2ebf0-32b8-4b70-8123-afc9f07f7669] Performed MessengerDeliverJob (Job ID: e7e2ebf0-32b8-4b70-8123-afc9f07f7669) from Async(default) in 3565.55ms
```

**Comment by jgraichen** [comment]
An internal error happens in the request but in `redmine_checklists`:

```
[eb73df07-5210-4526-9cb1-0f334c12cf4f] NoMethodError (undefined method `map' for nil:NilClass):
[eb73df07-5210-4526-9cb1-0f334c12cf4f]
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/app/models/journal_checklist_history.rb:139:in `force_object'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/app/models/journal_checklist_history.rb:60:in `initialize'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/lib/redmine_checklists/hooks/controller_issues_hook.rb:27:in `new'
[eb73df07-5210-4526-9cb1-0f334c12cf4f] plugins/redmine_checklists/lib/redmine_checklists/hooks/controller_issues_hook.rb:27:in `controller_issues_edit_after_save'
```

This plugin is called when an issue is changed, which also is when it is moved on a dashboard. I'll check why `rdbDADShowIssue` isn't working, but there still is a problem with `redmine_checklists`. 

Unfortunately, as far as I know, the plugin isn't open-source. Therefore, I cannot check what could be an error. You will have to ask the `redmine_checklists` developers to address that problem.

**Comment by qawsed55** [comment]
Thanks for reply. As I understand - `redmine_checklists` make some problem and for this problem there are error with `dashboard`. Is it right?
I have remake old version of `redmine_checklists` to work with RM 5.0, but as my expierience too bad, there are some errors in code.

**Comment by jgraichen** [comment]
> As I understand - redmine_checklists make some problem and for this problem there are error with dashboard. Is it right?

Yes. The flow works as that:

1) You move an issue.
2) The redmine dashboard updates the issue to the new state.
3) The redmine checklists plugin is called when any issue is updated and runs some code.
4) That code produces an error.
